CXX := g++
CXXFLAGS := -std=c++17 -Wall -I./src
LDFLAGS :=

SRC_DIR := src
TEST_DIR := $(SRC_DIR)/__test__

CORE_SRC := $(SRC_DIR)/Core/EntityManager/EntityManager.cpp \
			$(SRC_DIR)/Core/Entity/Entity.cpp \
            $(SRC_DIR)/Core/ComponentRegistry/ComponentRegistry.cpp

# -------------------------------
# Tests disponibles
# -------------------------------
TESTS := component entity entity_manager \
         transform renderable camera selectable primitives

BINARIES := $(TESTS:%=test_%)

all: $(BINARIES)

# -------------------------------
# Compilation des tests "Core"
# -------------------------------
test_component: $(TEST_DIR)/TestComponentRegistry.cpp $(CORE_SRC)
	$(CXX) $(CXXFLAGS) $^ -o $@ $(LDFLAGS)

test_entity: $(TEST_DIR)/TestEntity.cpp $(CORE_SRC)
	$(CXX) $(CXXFLAGS) $^ -o $@ $(LDFLAGS)

test_entity_manager: $(TEST_DIR)/TestEntityManager.cpp $(CORE_SRC)
	$(CXX) $(CXXFLAGS) $^ -o $@ $(LDFLAGS)

# -------------------------------
# Compilation des tests "Phase 2"
# -------------------------------
test_transform: $(TEST_DIR)/TestTransform.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@ $(LDFLAGS)

test_renderable: $(TEST_DIR)/TestRenderable.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@ $(LDFLAGS)

test_camera: $(TEST_DIR)/TestCamera.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@ $(LDFLAGS)

test_selectable: $(TEST_DIR)/TestSelectable.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@ $(LDFLAGS)

test_primitives: $(TEST_DIR)/TestPrimitives.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@ $(LDFLAGS)

# -------------------------------
# Raccourcis d'exécution
# -------------------------------
component: test_component
	./test_component

entity: test_entity
	./test_entity

entityManager: test_entity_manager
	./test_entity_manager

transform: test_transform
	./test_transform

renderable: test_renderable
	./test_renderable

camera: test_camera
	./test_camera

selectable: test_selectable
	./test_selectable

primitives: test_primitives
	./test_primitives

# -------------------------------
# Nettoyage
# -------------------------------
clean:
	rm -f $(BINARIES)
