CXX := g++
CXXFLAGS := -std=c++17 -Wall -I./src
LDFLAGS :=

SRC_DIR := src
TEST_DIR := $(SRC_DIR)/__test__

CORE_SRC := $(SRC_DIR)/Core/Entity/Entity.cpp \
            $(SRC_DIR)/Core/ComponentRegistry/ComponentRegistry.cpp

TESTS := component entity

BINARIES := $(TESTS:%=test_%)

all: $(BINARIES)

test_component: $(TEST_DIR)/testComponentRegistry.cpp $(CORE_SRC)
	$(CXX) $(CXXFLAGS) $^ -o $@ $(LDFLAGS)

test_entity: $(TEST_DIR)/testEntity.cpp $(CORE_SRC)
	$(CXX) $(CXXFLAGS) $^ -o $@ $(LDFLAGS)

entity: test_entity
	./test_entity

component: test_component
	./test_component

clean:
	rm -f $(BINARIES)
